version: "3"
services: 
  api:
    image: fastapi:latest
    ports: 
       - 8000:8000

    environment:
       - DATABASE_HOSTNAME=postgres
       - DATABASE_PORT=5432
       - DATABASE_PASSWORD=JamesMemba
       - DATABASE_NAME=fastapi
       - DATABASE_USERNAME=postgres
       - SECRET_KEY=P@u90fX!k3VrQmZ7&tN4Gw%yXcLp$1DhKeRb8HsVo2^TaMzEnLd6JcUy0BmWxYqS
       - ALGORITHM=HS256
       - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on: 
       - postgres
  postgres: 
     image: postgres
     environment: 
       - POSTGRES_PASSWORD=JamesMemba
       - POSTGRES_DB=fastapi

     volumes: 
       - postgres-db:/var/lib/postgresql/data

volumes: 
   postgres-db: 

