"""added the phone_number_column to users table

Revision ID: 1eb00c68046e
Revises: b9798c4c1940
Create Date: 2025-06-14 09:48:49.192641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb00c68046e'
down_revision: Union[str, None] = 'b9798c4c1940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
   
    # ### end Alembic commands ###
